name: enviro
channels:
  - conda-forge
dependencies:
  - folium
  - geopandas
  - ipympl
  - leafmap
  - matplotlib
  - numpy
  - planetary-computer
  - pystac-client
  - rioxarray
  - shapely
  - scikit-image
  - xarray
